### ISSUE TITLE
Error demeteorizing related to Cordova for Android

### ISSUE THREAD

**Issue by afuggini** [onmodulus/demeteorizer#155]
Getting this when demeteorizing:

```
Demeteorizing application...

WARNING: The output directory is under your source tree.

=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error: /Users/southernmedia/Documents/SM/www/Sulvo/Experimental/leaderboard/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit code 2
   Error output:
   [Error: Please install Android target: "android-22".

   Hint: Open the SDK manager by running: /usr/local/Cellar/android-sdk/24.2/bin/android
   You will require:
   1. "SDK Platform" for android-22
   2. "Android SDK Platform-tools (latest)
   3. "Android SDK Build-tools" (latest)]
   at ChildProcess.whenDone
   (/Users/southernmedia/.meteor/packages/meteor-tool/.1.1.10.3wrbh0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)
Conversion failed.
```

Any ideas?

**Comment by prashanthmadi** [comment]
+1

were you able to fix this ? I landed in similar issue

**Comment by fiveisprime** [comment]
Run `$ meteor remove-platform android` to prevent building android. :+1:
