### ISSUE TITLE
Failed at the fibers@1.05 install

### ISSUE THREAD

**Issue by ralphievolt** [onmodulus/demeteorizer#159]
I am running on windows and got error after npm install command
```
D:\METEORJS\codeGenerator2>demeteorizer
Demeteorizing application...

WARNING: The output directory is under your source tree.

Demeteorization complete.

D:\METEORJS\codeGenerator2>cd .demeteorized/bundle/programs/server

D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server>npm install

> fibers@1.0.5 install D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server\node_modules\fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server\node_modules\fibers
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
meteor-dev-bundle@0.0.0 D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server
├─┬ chalk@0.5.1
│ ├── ansi-styles@1.1.0
│ ├── escape-string-regexp@1.0.3
│ ├─┬ has-ansi@0.1.0
│ │ └── ansi-regex@0.2.1
│ ├── strip-ansi@0.3.0
│ └── supports-color@0.2.0
├─┬ eachline@2.3.3
│ └── type-of@2.0.1
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
└── underscore@1.5.2

npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No description
npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No repository field.
npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\METEORJS\codeGenerator2\.demeteorized\bundle\programs\server\npm-debug.log
'''

**Comment by sjmcdowall** [comment]
Well one error maybe because you are using node 5 for the npm install, where as meteor was built around node 0.10.40 (current).  Can you nvm node 0.10.40 in and see if the "npm install" works better?  However, you WILL undoubtedly need to compile fibers even then.  For that you will need the full VS12 C++ AND Command Line build tools installed.

**Comment by ralphievolt** [comment]
Is VS12 C++ Redistributable enough? What do you mean by "Command Line build tools installed" and how do I go about it?  Thanks.

**Comment by sjmcdowall** [comment]
@ralphievolt -- No, alas you need the full VS 2012 studio environment for a "deployment" environment .. See my post on the meteor forums for deploying to windows for some ideas that may help : https://forums.meteor.com/t/one-deployment-method-for-a-meteor-application-on-windows/13928
