### ISSUE TITLE
After changing MONGO_URL, deploy fails with CLI tool v4 and gives a runtime error with CLI tool v5

### ISSUE THREAD

**Issue by kareems** [onmodulus/demeteorizer#168]
I changed the MONGO_URL on my app, redeployed with the Modulus command line tool v5.0.1, and on restart, the app started giving this runtime error:

```
> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


/mnt/app/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
TypeError: Cannot read property 'master' of undefined
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /mnt/app/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at packages/mongo/mongo_driver.js:183:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
```

I tried downgrading the command line tool to v4 (it went to 4.0.2), and that can't get through the `modulus deploy` command. It gives the following error:

```
$ modulus deploy -p 'project-name'
Welcome to Modulus
You are logged in as kareems
Selecting project-name

Meteor project detected...
Input:  /path/to/my/project
Output: /path/to/my/project/.demeteorized
Determining Meteor version...
Meteor version: 1.2.1
Bundling Meteor App...
This command has been deprecated in favor of 'meteor build', which allows you
to build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build' for more information.


WARNING: The output directory is under your source tree.
meteor bundle generation complete.
Finding dependencies...
fs.js:849
  return binding.stat(pathModule._makeLong(path));
                                 ^

Error: ENOENT: no such file or directory, stat '/path/to/my/project/.demeteorized/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/.#README.md'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at Demeteorizer.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/demeteorizer/lib/demeteorizer.js:232:20)
    at Array.forEach (native)
    at Demeteorizer.findDependenciesInFolder (/usr/local/lib/node_modules/modulus/node_modules/demeteorizer/lib/demeteorizer.js:231:26)
    at Demeteorizer.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/demeteorizer/lib/demeteorizer.js:250:14)
    at Array.forEach (native)
    at Demeteorizer.findDependenciesInFolder (/usr/local/lib/node_modules/modulus/node_modules/demeteorizer/lib/demeteorizer.js:231:26)
    at Demeteorizer.<anonymous> (/usr/local/lib/node_modules/modulus/node_modules/demeteorizer/lib/demeteorizer.js:250:14)
    at Array.forEach (native)
```

The support engineer asked me to submit this as an issue here.

**Comment by topaztee** [comment]
Did you get this fixed? I have the same issue.

**Comment by harlanj** [comment]
@topaztee @kareems is this still an issue for you two? Sorry for responding to your issue so late. If this isn't a problem anymore let me know and I'll close the issue for you.

**Comment by kareems** [comment]
@harlanj fixed for me, although it was a few months ago and I'm afraid I don't remember the fix.

**Comment by harlanj** [comment]
@kareems I'll close the issue for now then. Once again, sorry for the delayed response. If this comes back up, just reopen the issue with some details. Have a great one!
