### ISSUE TITLE
Failing because of meteor-dev-bundle@0.0.0

### ISSUE THREAD

**Issue by csellis** [onmodulus/demeteorizer#173]
Console: 
```
`Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


/mnt/app/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [Rheel4$:27017]
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /mnt/app/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


/mnt/app/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [Rheel4$:27017]
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /mnt/app/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


/mnt/app/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [Rheel4$:27017]
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /mnt/app/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main


/mnt/app/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [Rheel4$:27017]
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /mnt/app/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/mnt/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main`
```

Updated NPM

**Comment by fiveisprime** [comment]
It's failing when trying to connect to the database

`Error: failed to connect to [Rheel4$:27017]`

Looks like your `MONGO_URL` is set to `Rheel4$:27017`, which isn't a valid connection string.

**Comment by csellis** [comment]
@fiveisprime Isn't that set in the website?

**Comment by harlanj** [comment]
@csellis That's set on the admin page of your project.

`https://my.modulus.io/project/<id>/admin`

**Comment by csellis** [comment]
@harlanj Problem occurs with one of the special characters I had in my password

**Comment by harlanj** [comment]
Since this is outside of the scope of the Modulus CLI, I'm going to leave this issue closed. You can open a ticket with support and we can take better care of you there. You can come into the IRC too
