### ISSUE TITLE
Upgrading to 4.0.0 with node 0.10.43

### ISSUE THREAD

**Issue by louis49** [onmodulus/demeteorizer#194]
demeteorizer/node_modules/hoek/lib/index.js:5
const Crypto = require('crypto');

^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/VoxingPro-Web/node_modules/demeteorizer/lib/demeteorizer.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Using node 0.10.43

**Comment by fiveisprime** [comment]
Demeteorizer doesn't support node <4.x.x starting at version 4.0.0. We're pushing node forward and using some ES2015 features now. :)

**Comment by louis49** [comment]
Thank you
