### ISSUE TITLE
 The output directory is under your source tree

### ISSUE THREAD

**Issue by beenadevi** [onmodulus/demeteorizer#211]
When i deploy the project in meteor then i got this error please help me asap.

The output directory is under your source tree.Your generated files may get interpreted as source code!Consider building into a different directory instead meteor build ../output buffer.js:106

throw new error(
^ 

error : if encoding is specified then first argument must be a string
at new buffer(buffer.js:106:13)
at readable.<anonymous>(c:\users\name\appdata\roaming\npm_modules\mup\node_module\archiver\lib\util\inde.js:32:15)
at emitnone(events.js:91:20)
at endReadNT(_stream_readable.js:926:12)
at _combinedTickCallback(internal/process/next_tick.js:74:11)
at process._tickCallback(internal/process/next_tick.js:98:9)

**Comment by harlanj** [comment]
Hey  @beenadevi sorry for the issues. What was the `demeteorizer` command you ran? Also, can you list the flags you may have included? What version of `demeteorizer` are you using? What version of node are you running as well?

**Comment by harlanj** [comment]
@beenadevi I'm going to close this issue for now. If you feel the need to reopen just do so and we'll get back to solving your problem!
