### ISSUE TITLE
error with NPM start

### ISSUE THREAD

**Issue by jkd65** [onmodulus/demeteorizer#237]
I am having an issue running npm start on windows and am getting this error.

```
> meteor-dev-bundle@0.0.0 start F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server
> node ../../main

F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: double colon in host identifier
    at module.exports (F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\url_parser.js:91:13)
    at connect (F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\mongo_client.js:266:16)
    at Function.MongoClient.connect (F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\mongo_client.js:113:3)
    at new MongoConnection (packages/mongo/mongo_driver.js:174:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp\.demeteorized\bundle\programs\server\npm-debug.log
```

Any help is greatly appreciated, and I can provide more info on request.

**Comment by jackboberg** [comment]
This seems related: [Error: “Double colon in host identifer”](http://stackoverflow.com/questions/36206686/error-double-colon-in-host-identifer)

**Comment by fiveisprime** [comment]
@jkd65 Be sure that you are *not* including a trailing `/` when providing your `ROOT_URL` environment variable.

I'm closing this as it's not related to Demeteorizer, but feel free to re-open it or respond if you have additional questions/comments.
