### ISSUE TITLE
"npm start" error on Linux

### ISSUE THREAD

**Issue by antxa** [onmodulus/demeteorizer#283]
Hi,
After demeteorizing, I run "npm install" with success. But I get an error when I run "npm start":

```
meteor-dev-bundle@0.0.0 start /sc01a4/users/jibotusa/proiektuak/LIHLITH/apps/tutorial-simple-todos/.demeteorized/bundle/programs/server
> node ../../main

/sc01a4/users/jibotusa/proiektuak/LIHLITH/apps/tutorial-simple-todos/.demeteorized/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/sc01a4/users/jibotusa/proiektuak/LIHLITH/apps/tutorial-simple-todos/.demeteorized/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/sc01a4/users/jibotusa/proiektuak/LIHLITH/apps/tutorial-simple-todos/.demeteorized/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/sc01a4/users/jibotusa/proiektuak/LIHLITH/apps/tutorial-simple-todos/.demeteorized/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)

npm ERR! Linux 2.6.32-696.18.7.el6.x86_64
npm ERR! argv "/soft_orokorra_linux_x86_64_rhel6/nodejs-4.6/bin/node" "/soft_orokorra_linux_x86_64_rhel6/nodejs-4.6/bin/npm" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main

```
Could you help me?
Thanks!

**Comment by groupfranchising** [comment]
Have you found a solution for this? I am getting the exact same error on Linux.

**Comment by antxa** [comment]
No, I haven't.
