### ISSUE TITLE
Error occurred, type: error, text: Invalid path for filesystem

### ISSUE THREAD

**Issue by nwabdou85** [onmodulus/demeteorizer#284]
I used to deploy my app without any problem;

starting from two days ago; is branch is updated but can't update the web site (react - meteor app);
remote: Error - Changes committed to remote repository but deployment to website failed.
here is the error in log streaming

```
2018-07-02T19:01:33              Error occurred, type: error, text: Invalid path for filesystem 'D:/home/site/repository/programs/server/npm/node_modules/meteor/montiapm_agent-binary-deps/node_modules/v8-profiler/build/Release/.deps/tmp/mt-1qb8e7n.aehs/npm/node_modules/.temp-1mz6eut.xdbmf/node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-linux-x64/.gitattributes': The data area passed to a system call is too small.
, stackTrace:    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositorySafeHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
   at LibGit2Sharp.Repository.Checkout(Tree tree, CheckoutOptions checkoutOptions, String headTarget, String refLogHeadSpec, Signature signature)
   at LibGit2Sharp.Repository.Checkout(Branch branch, CheckoutOptions options, Signature signature)
   at LibGit2Sharp.Repository.Checkout(String committishOrBranchSpec, CheckoutOptions options, Signature signature)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.Update(String id) in C:\Kudu Files\Private\src\master\Kudu.Core\SourceControl\Git\LibGit2SharpRepository.cs:line 193
   at Kudu.Core.Deployment.DeploymentManager.<DeployAsync>d__24.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\DeploymentManager.cs:line 207
2018-07-02T19:01:33            Error occurred, type: error, text: One or more errors occurred., stackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Kudu.Console.Program.PerformDeploy(String appRoot, String wapTargets, String deployer, String lockPath, IEnvironment env, IDeploymentSettingsManager settingsManager, TraceLevel level, ITracer tracer, ITraceFactory traceFactory, IOperationLock deploymentLock), innerText: Deployment failed, innerStackTrace:    at Kudu.Core.Deployment.DeploymentManager.<DeployAsync>d__24.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\DeploymentManager.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Console.Program.<>c__DisplayClass1_0.<<PerformDeploy>b__1>d.MoveNext()
```

Any solution to this??

**Comment by prashanthmadi** [comment]
It has hit max path size.. try with npm>3 while installing packages and that might resolve the issue.

D:/home/site/repository/programs/server/npm/node_modules/meteor/montiapm_agent-binary-deps/node_modules/v8-profiler/build/Release/.deps/tmp/mt-1qb8e7n.aehs/npm/node_modules/.temp-1mz6eut.xdbmf/node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-linux-x64/.gitattributes

**Comment by nwabdou85** [comment]
Thank's for a erply 


I used npm > 3

  "engines": {
    "node": "8.8.1",
    "npm": "3.10.9"
  },

before works perfectly , but since Two days not.

Is there another solution ?
